package com.agarcia.pdm_course_2026.clase220426.dummy

import com.agarcia.pdm_course_2026.clase220426.model.Movie

val dummyMovies = listOf(
  Movie(
    id = 1226863,
    title = "Super Mario Galaxy la película",
    originalTitle = "The Super Mario Galaxy Movie",
    originalLanguage = "en",
    overview = "Secuela de 'Super Mario Bros: La película', basada en la saga 'Mario Galaxy'. Los hermanos Mario y Luigi y la princesa Peach emprenden una aventura hasta los confines del espacio y a través de la galaxia.",
    releaseDate = "2026-04-01",
    adult = false,
    genreIds = listOf(10751, 35, 12, 14, 16),
    popularity = 683.1411,
    voteAverage = 6.751,
    voteCount = 549,
    video = false,
    backdropUrl = "https://image.tmdb.org/t/p/w500/kxQiIJ4gVcD3K6o14MJ72p5yRcE.jpg",
    posterUrl = "https://image.tmdb.org/t/p/w500/79EVB4qhyfrdlMgT8GIRAikdzsQ.jpg"
  ),
  Movie(
    id = 1523145,
    title = "Твоё сердце будет разбито",
    originalTitle = "Твоё сердце будет разбито",
    originalLanguage = "ru",
    overview = "",
    releaseDate = "2026-03-26",
    adult = false,
    genreIds = listOf(10749, 18),
    popularity = 394.992,
    voteAverage = 6.93,
    voteCount = 71,
    video = false,
    backdropUrl = "https://image.tmdb.org/t/p/w500/1x9e0qWonw634NhIsRdvnneeqvN.jpg",
    posterUrl = "https://image.tmdb.org/t/p/w500/iGpMm603GUKH2SiXB2S5m4sZ17t.jpg"
  ),
  Movie(
    id = 980431,
    title = "La leyenda de Aang: El último Airbender",
    originalTitle = "Avatar Aang: The Last Airbender",
    originalLanguage = "en",
    overview = "Película de animación que seguirá a Aang y sus amigos, ahora como jóvenes adultos, varios años después de los acontecimientos del final de 'Avatar: The Last Airbender'.",
    releaseDate = "2026-10-09",
    adult = false,
    genreIds = listOf(16, 28, 12, 14),
    popularity = 311.9385,
    voteAverage = 0.0,
    voteCount = 0,
    video = false,
    backdropUrl = "https://image.tmdb.org/t/p/w500/sS3zGYFPcfM5pArVNWl6qLyaSmU.jpg",
    posterUrl = "https://image.tmdb.org/t/p/w500/iMsORWhD8MawINagL6kvpDVAtS.jpg"
  ),
  Movie(
    id = 83533,
    title = "Avatar: Fuego y ceniza",
    originalTitle = "Avatar: Fire and Ash",
    originalLanguage = "en",
    overview = "Jake Sully y Neytiri enfrentan una nueva amenaza en Pandora: los Ash People, una tribu Na'vi violenta y sedienta de poder, liderada por la implacable Varang. Tras la devastadora guerra contra la RDA y la pérdida de su hijo mayor, la familia de Jake deberá luchar por su supervivencia y el futuro de Pandora en un conflicto que llevará a los personajes a sus límites emocionales y físicos.",
    releaseDate = "2025-12-17",
    adult = false,
    genreIds = listOf(878, 12, 14),
    popularity = 278.0031,
    voteAverage = 7.372,
    voteCount = 2678,
    video = false,
    backdropUrl = "https://image.tmdb.org/t/p/w500/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg",
    posterUrl = "https://image.tmdb.org/t/p/w500/4n1U0Mwn7djux6VKNYDRWPgS2x6.jpg"
  ),
  Movie(
    id = 1198994,
    title = "SEND HELP (Enviad ayuda)",
    originalTitle = "Send Help",
    originalLanguage = "en",
    overview = "Después de que un accidente de avión deje varados en una isla remota a una competente empleada y a su insoportable jefe, ella deberá utilizar sus habilidades de supervivencia para mantenerlos a ambos con vida, a pesar de su difícil relación.",
    releaseDate = "2026-01-22",
    adult = false,
    genreIds = listOf(27, 53, 35),
    popularity = 294.8435,
    voteAverage = 7.04,
    voteCount = 1051,
    video = false,
    backdropUrl = "https://image.tmdb.org/t/p/w500/gCmfeKmEAZBP5gcXpiqb0gii9rS.jpg",
    posterUrl = "https://image.tmdb.org/t/p/w500/qXZZtyzuTX3KMfSLssCR6J0mODd.jpg"
  ),
  Movie(
    id = 1613798,
    title = "Venganza",
    originalTitle = "Venganza",
    originalLanguage = "es",
    overview = "Carlos y Miguel son dos soldados de élite de las fuerzas especiales mexicanas y mejores amigos cuyas vidas cambian para siempre cuando Carlos es testigo del brutal asesinato de su esposa por manos de un despiadado asesino.",
    releaseDate = "2026-02-26",
    adult = false,
    genreIds = listOf(28, 53),
    popularity = 255.8103,
    voteAverage = 6.7,
    voteCount = 61,
    video = false,
    backdropUrl = "https://image.tmdb.org/t/p/w500/jJmlCFi5EjpH5vHmOczRiVDm0qS.jpg",
    posterUrl = "https://image.tmdb.org/t/p/w500/ggJGx8fwwy21gEIXYusIlHcUn8z.jpg"
  ),
  Movie(
    id = 687163,
    title = "Proyecto Salvación",
    originalTitle = "Project Hail Mary",
    originalLanguage = "en",
    overview = "El profesor de ciencias Ryland Grace se despierta en una nave espacial a años luz de casa sin recordar quién es ni cómo ha llegado hasta allí. A medida que recupera la memoria, empieza a descubrir su misión: resolver el enigma de la misteriosa sustancia que provoca la extinción del sol.",
    releaseDate = "2026-03-15",
    adult = false,
    genreIds = listOf(878, 12),
    popularity = 227.7113,
    voteAverage = 8.221,
    voteCount = 1632,
    video = false,
    backdropUrl = "https://image.tmdb.org/t/p/w500/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg",
    posterUrl = "https://image.tmdb.org/t/p/w500/7lwOTxajURKEWO6gI370NTrVdBO.jpg"
  ),
  Movie(
    id = 1470130,
    title = "The Mortuary Assistant",
    originalTitle = "The Mortuary Assistant",
    originalLanguage = "en",
    overview = "Rebecca Owens, una licenciada en ciencias mortuorias, acepta un trabajo nocturno en la funeraria River Fields. Lo que comienza como un trabajo rutinario pronto se vuelve siniestro al enfrentarse a terroríficas fuerzas sobrenaturales.",
    releaseDate = "2026-02-13",
    adult = false,
    genreIds = listOf(27, 9648),
    popularity = 209.066,
    voteAverage = 5.481,
    voteCount = 77,
    video = false,
    backdropUrl = "https://image.tmdb.org/t/p/w500/gM1kQRPwOVW1Eos5tVWqcYmHR5S.jpg",
    posterUrl = "https://image.tmdb.org/t/p/w500/3loVbnQ9hmay4OA6QjV6yMpHRYf.jpg"
  ),
  Movie(
    id = 1327819,
    title = "Hoppers",
    originalTitle = "Hoppers",
    originalLanguage = "en",
    overview = "Una amante de los animales aprovecha la oportunidad de utilizar una tecnología que coloca su conciencia en un castor robótico, descubriendo misterios dentro del mundo animal que van más allá de lo que podría haber imaginado.",
    releaseDate = "2026-03-04",
    adult = false,
    genreIds = listOf(16, 10751, 878, 35, 12),
    popularity = 191.3328,
    voteAverage = 7.585,
    voteCount = 496,
    video = false,
    backdropUrl = "https://image.tmdb.org/t/p/w500/u53UYu5XG2hNgWGvs3xGhAVzypl.jpg",
    posterUrl = "https://image.tmdb.org/t/p/w500/4Z0E1W7YvQ0aVtgj7KKtktb9ukd.jpg"
  ),
  Movie(
    id = 1290821,
    title = "Shelter: El Protector",
    originalTitle = "Shelter",
    originalLanguage = "en",
    overview = "Un recluso en una remota isla escocesa rescata a una niña del mar, desencadenando una peligrosa secuencia de acontecimientos.",
    releaseDate = "2026-01-28",
    adult = false,
    genreIds = listOf(28, 80, 53),
    popularity = 194.5063,
    voteAverage = 6.788,
    voteCount = 582,
    video = false,
    backdropUrl = "https://image.tmdb.org/t/p/w500/nHxWyy18SvAZ8jJeemtS8k1UNjM.jpg",
    posterUrl = "https://image.tmdb.org/t/p/w500/kOsqd5jFZ0p3O8Z0k0VQvBW2neW.jpg"
  ),
  Movie(
    id = 1084577,
    title = "Balls Up: Con un par",
    originalTitle = "Balls Up",
    originalLanguage = "en",
    overview = "Los ejecutivos de marketing Brad y Elijah lanzan un audaz patrocinio de preservativos de cobertura total directamente a la Copa del Mundo. Después de que su ebria celebración en Brasil desencadene un escándalo mundial, deberán huir de hinchas furiosos, delincuentes y funcionarios sedientos de poder para salvar sus carreras.",
    releaseDate = "2026-04-15",
    adult = false,
    genreIds = listOf(35, 28, 12),
    popularity = 190.1378,
    voteAverage = 5.6,
    voteCount = 101,
    video = false,
    backdropUrl = "https://image.tmdb.org/t/p/w500/jRsjWwZzI39bTm44FNhRtiICd9k.jpg",
    posterUrl = "https://image.tmdb.org/t/p/w500/50V1E3NE3UDFmq0fhMpByx1b4Ka.jpg"
  ),
  Movie(
    id = 1290417,
    title = "Embestida",
    originalTitle = "Thrash",
    originalLanguage = "en",
    overview = "Cuando un catastrófico huracán azota un pueblo costero, el nivel del mar sube rápidamente y sus habitantes deben sobrevivir a un montón de hambrientos tiburones.",
    releaseDate = "2026-04-10",
    adult = false,
    genreIds = listOf(27, 53),
    popularity = 168.6483,
    voteAverage = 5.991,
    voteCount = 378,
    video = false,
    backdropUrl = "https://image.tmdb.org/t/p/w500/3ooXDVaz4xHKtwe4lkmF1gNopOC.jpg",
    posterUrl = "https://image.tmdb.org/t/p/w500/osYy4GDE4nr69MGTJxRaZlqU82S.jpg"
  ),
  Movie(
    id = 840464,
    title = "Greenland 2: Migración",
    originalTitle = "Greenland 2: Migration",
    originalLanguage = "en",
    overview = "La familia Garrity superviviente debe abandonar la seguridad del búnker de Groenlandia y embarcarse en un peligroso viaje a través del diezmado páramo helado de Europa para encontrar un nuevo hogar.",
    releaseDate = "2026-01-07",
    adult = false,
    genreIds = listOf(12, 53, 878),
    popularity = 182.1379,
    voteAverage = 6.5,
    voteCount = 894,
    video = false,
    backdropUrl = "https://image.tmdb.org/t/p/w500/wns4x1GyxCudgOZRyhXKjXVJf3T.jpg",
    posterUrl = "https://image.tmdb.org/t/p/w500/d6LG93i2sDaYpavISSM9t47C2Qy.jpg"
  ),
  Movie(
    id = 1304313,
    title = "La momia de Lee Cronin",
    originalTitle = "Lee Cronin's The Mummy",
    originalLanguage = "en",
    overview = "La joven hija de un periodista desaparece en el desierto sin dejar rastro—ocho años más tarde, la familia rota se conmociona cuando ella es devuelta a ellos, y lo que debiera haber sido una reunión jubilosa se convierte en una auténtica pesadilla.",
    releaseDate = "2026-04-15",
    adult = false,
    genreIds = listOf(27, 9648),
    popularity = 171.6298,
    voteAverage = 6.903,
    voteCount = 118,
    video = false,
    backdropUrl = "https://image.tmdb.org/t/p/w500/zc08qkHtWfZ2cQGQBK1S5yafJmR.jpg",
    posterUrl = "https://image.tmdb.org/t/p/w500/hGgSpTX2f3ShFD41Ul0vcY3DSHb.jpg"
  ),
  Movie(
    id = 1171145,
    title = "Ruta de escape",
    originalTitle = "Crime 101",
    originalLanguage = "en",
    overview = "Davis es un escurridizo ladrón cuyos atracos de alto riesgo tienen desconcertada a la policía. Davis está planeando su mayor golpe, con la esperanza de que sea el último, cuando se cruza en su camino Sharon, una desilusionada ejecutiva de seguros.",
    releaseDate = "2026-02-11",
    adult = false,
    genreIds = listOf(80, 53),
    popularity = 140.4731,
    voteAverage = 7.0,
    voteCount = 746,
    video = false,
    backdropUrl = "https://image.tmdb.org/t/p/w500/vG42HeYtoTFflqwP42wYD7tBuNr.jpg",
    posterUrl = "https://image.tmdb.org/t/p/w500/oUF0tTmbwlfkhiYSU5nXJccr5K0.jpg"
  ),
  Movie(
    id = 502356,
    title = "Super Mario Bros: La película",
    originalTitle = "The Super Mario Bros. Movie",
    originalLanguage = "en",
    overview = "Mientras trabajan en una avería subterránea, los fontaneros de Brooklyn, Mario y su hermano Luigi, viajan por una misteriosa tubería hasta un nuevo mundo mágico. Pero, cuando los hermanos se separan, Mario deberá emprender una épica misión para encontrar a Luigi.",
    releaseDate = "2023-04-05",
    adult = false,
    genreIds = listOf(10751, 35, 12, 14, 16),
    popularity = 132.1767,
    voteAverage = 7.587,
    voteCount = 10506,
    video = false,
    backdropUrl = "https://image.tmdb.org/t/p/w500/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg",
    posterUrl = "https://image.tmdb.org/t/p/w500/k36QyeVsy851npTUQL08jO8hqip.jpg"
  ),
  Movie(
    id = 1010755,
    title = "Strangers: Capítulo 3",
    originalTitle = "The Strangers: Chapter 3",
    originalLanguage = "en",
    overview = "Los supervivientes se enfrentan a nuevas amenazas de extraños enmascarados. Secretos salen a la luz, poniendo en peligro sus vidas mientras la línea entre realidad y peligro se difumina en su lucha por sobrevivir.",
    releaseDate = "2026-02-05",
    adult = false,
    genreIds = listOf(27, 53),
    popularity = 139.5821,
    voteAverage = 5.672,
    voteCount = 116,
    video = false,
    backdropUrl = "https://image.tmdb.org/t/p/w500/fPfDB0IHOqvmKIzFP9CA51OOS1N.jpg",
    posterUrl = "https://image.tmdb.org/t/p/w500/mIiwoDukWkEoo90WXqOHxHmwhYD.jpg"
  ),
  Movie(
    id = 1641319,
    title = "Sniper: En tierra de nadie",
    originalTitle = "Sniper: No Nation",
    originalLanguage = "en",
    overview = "Cuando el francotirador Brandon Beckett es tachado de terrorista, se ve obligado a desaparecer y embarcarse en una misión de rescate imposible junto a su legendario padre.",
    releaseDate = "2026-04-07",
    adult = false,
    genreIds = listOf(28, 53),
    popularity = 138.8777,
    voteAverage = 6.2,
    voteCount = 33,
    video = false,
    backdropUrl = "https://image.tmdb.org/t/p/w500/7lizs4SuEU2ihkkAa0SZ66NtHbl.jpg",
    posterUrl = "https://image.tmdb.org/t/p/w500/hdSt80XqI2IWu9WOWZQVecuPT7D.jpg"
  ),
  Movie(
    id = 1297842,
    title = "GOAT: Como cabras",
    originalTitle = "GOAT",
    originalLanguage = "en",
    overview = "Will es una pequeña cabra con grandes sueños que recibe una oportunidad única en la vida para unirse a los profesionales y jugar al rugebol, un deporte de alta intensidad, mixto y de contacto total dominado por los animales más rápidos y feroces del mundo.",
    releaseDate = "2026-02-11",
    adult = false,
    genreIds = listOf(16, 35, 10751),
    popularity = 133.4087,
    voteAverage = 7.9,
    voteCount = 418,
    video = false,
    backdropUrl = "https://image.tmdb.org/t/p/w500/tq3h43fZy0H80vzf47MAY7R9Mxo.jpg",
    posterUrl = "https://image.tmdb.org/t/p/w500/l8Y8o3RpFg54gmQQ8GVaxVroFmY.jpg"
  ),
  Movie(
    id = 1311031,
    title = "Guardianes de la noche: Kimetsu no Yaiba La fortaleza infinita",
    originalTitle = "劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来",
    originalLanguage = "ja",
    overview = "El Cuerpo de Cazadores de Demonios se enfrenta a los Doce Kizuki restantes antes de enfrentarse a Muzan en el Castillo del Infinito para derrotarlo de una vez por todas.",
    releaseDate = "2025-07-18",
    adult = false,
    genreIds = listOf(16, 28, 14),
    popularity = 129.2603,
    voteAverage = 7.7,
    voteCount = 807,
    video = false,
    backdropUrl = "https://image.tmdb.org/t/p/w500/1RgPyOhN4DRs225BGTlHJqCudII.jpg",
    posterUrl = "https://image.tmdb.org/t/p/w500/iWLV12z9oexSRLz2WKyqCZbKoPA.jpg"
  ),
)